# Lab 2 - Fundamentals of Python II


## Conditionals

`None`, `0`, and empty strings/lists/dicts/tuples all evaluate to `False`. All other values are `True`.

In [1]:
print(bool(0))
print(bool(""))
print(bool([]))
print(bool({}))
print(bool(()))

False
False
False
False
False


Note the colon at the end of the `if` and `else`, as well as the indentation

In [2]:
x = 10
if x % 2 == 0:
    print('x is even!')
else:
    print('x is odd!')

x is even!


Else if statements are written `elif`

In [3]:
x = 10
if x < 0:
    print('x is negative')
elif x > 0:
    print('x is positive')
else:
    print('x is zero')

x is positive


Checking if an element exists in an array can be done using the `in` operator

In [4]:
grades = ['A', 'C', 'B', 'B']

if 'A' in grades:
    print('Nice!')
elif 'B' in grades:
    print('Pretty good!')
else:
    print('Better luck next time')

Nice!


`if` can be used as an inline expression, like Java/C's ternary operator `bool_expr ? val1 : val2`

In [5]:
day = "Monday"
day_type = "Weekend" if day in ["Friday", "Saturday"] else "Weekday"
day_type

'Weekday'

## Loops

### Looping over lists

Looping over an array is possible using a foreach style loop

In [6]:
array = [1,2,3,4,5]

for element in array:
    print(element)

1
2
3
4
5


If you need the indicies, instead of the traditional while loop
```python
i = 0
while i < len(array):
    array[i] * = 2
    i += 1
```
consider the more concise alternative using the built-in `range` function

In [7]:
array = [1,2,3,4,5]

for i in range(len(array)):
    array[i] *= 2
array

[2, 4, 6, 8, 10]

From the documentation, `range` returns an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step

In [8]:
print( range(1,10,2) )
print( list(range(1,10,2)) ) # you can cast it to a list if you want to use it like one

range(1, 10, 2)
[1, 3, 5, 7, 9]


In Jupyter notebooks, you can quickly check the function's documentation by using a `?` instead of the function parameters.

P.S. see what happens when you use `?` on a variable like `array`

In [9]:
range?

Init signature: range(self, /, *args, **kwargs)
Docstring:     
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).
Type:           type
Subclasses:     


### Looping over dictionaries

In [10]:
months = {
    "January": 1,
    "Feburary": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}

for month_name in months: # looping over keys
    print(month_name)

January
Feburary
March
April
May
June
July
August
September
October
November
December


In [11]:
for month_number in months.values(): # looping over values
    print(month_number)

1
2
3
4
5
6
7
8
9
10
11
12


In [12]:
for month_name, month_number in months.items(): # looping over key and value pairs
    print(month_name, month_number)

January 1
Feburary 2
March 3
April 4
May 5
June 6
July 7
August 8
September 9
October 10
November 11
December 12


## List comprehensions

List comprehensions provide a concise way of creating lists

In [13]:
# Using a for loop
squares = []
for i in range(1,11):
    squares.append(i**2)
squares

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [14]:
# Using list comprehension
squares = [i**2 for i in range(1,11)]
squares

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

List comprehension can include if conditions

In [15]:
# Using a for loop
squares = []
for i in range(1,11):
    if i**2 % 2 == 0:
        squares.append(i**2)
squares

[4, 16, 36, 64, 100]

In [16]:
# Equivalent code using list comprehension
squares = [i**2 for i in range(1,11) if i**2 % 2 == 0] # even squares
squares

[4, 16, 36, 64, 100]

In [17]:
# Making it a bit clearer / more readable by breaking it over multiple lines
# P.S. a line of code in python can be split over multiple lines as long as it's between brackets
squares = [
    i**2
    for i in range(1,11)
    if i**2 % 2 == 0
]
squares

[4, 16, 36, 64, 100]

And can also create nested lists

In [18]:
times_table = [[x*y for x in range(1,13)] for y in range(1,13)]
times_table

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24],
 [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36],
 [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48],
 [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
 [6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72],
 [7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84],
 [8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96],
 [9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99, 108],
 [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120],
 [11, 22, 33, 44, 55, 66, 77, 88, 99, 110, 121, 132],
 [12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144]]

**Exercise Break**

Solve Exercise(s): 1 - 4

## Functions

Functions don't need to return something (if not specified, returns `None` by default)

In [19]:
def greet():
    print('Hello there')

greet()

Hello there


You can specify parameters for the function to take in

In [20]:
def multiply(x, y):
    return x*y

multiply(10, 5)

50

You can add optional arguments by specifying a default value for the parameter

Here is a root function $\sqrt[n]{x^m}$ that calculates the square root $\sqrt{x}$ by default

In [21]:
def root(x, m=1, n=2):
    return x**(m/n)

root(9)

3.0

You can also explicitly assign the parameters with the arguments you are passing

In [22]:
root(x=8, n=3)

2.0

## Lambdas

Lambdas are simply anonymous (unnamed) functions, and are a very useful and concise way of applying data cleaning/processing steps over values in a dataset

In [23]:
# minimal example that takes a parameter x and returns x^2
lambda x: x**2

<function __main__.<lambda>(x)>

In [24]:
# calling it
(lambda x: x**2)(8)

64

In [25]:
# alternatively, storing the anonymous function in a variable for multiple calls
# P.S. not a good coding style, define a normal function instead
square = lambda x: x**2
print(square(8))
print(square(20))

64
400


Especially useful when used in conjuction with a function like `map` which applies a function to each element of a given collection

In [26]:
list(map(lambda x: x**2, [1,2,3,4,5]))

[1, 4, 9, 16, 25]

In [27]:
# Which is equivalent to:
def square(x):
    return x**2

list(map(square, [1,2,3,4,5]))

[1, 4, 9, 16, 25]

**Exercise Break**

Solve Exercise(s): 5 - 8

## A Short Introduction to Numpy

[NumPy](https://numpy.org/doc/stable/) is a Python library that adds support for large, multi-dimensional arrays and matrices, in addition to many high-level mathematical functions that can be applied to these arrays. [Source: Wikipedia](https://en.wikipedia.org/wiki/NumPy)

NumPy functions are very fast compared to normal Python looping and array manipulation, as it is implemented in C, and is the dataset loading/manipulation library (pandas) we'll be using next time is built on top of it.

In [28]:
# importing the library and giving it a short alias
import numpy as np

The trade-off for NumPy's performance is that you can no longer mix datatypes in an array

In [29]:
# to avoid data loss, the entire list is casted to str
np.array([1,2,3,4,'5'])

array(['1', '2', '3', '4', '5'], dtype='<U21')

One of the other main advantages of NumPy is supports vectorised operations

In [30]:
x = np.array([1,2,3,4,5,6,7,8,9])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# adds 10 to each element
x + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
# multiply each element by 2
x * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
# element-by-element boolean comparsion
x > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [34]:
# which you can use to filter the original array
x[x > 5]

array([6, 7, 8, 9])